CREATE TABLE USER(
		USER_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
		USER_NAME VARCHAR(20),
		PASSWD VARCHAR(20),
		E_MAIL VARCHAR(20),
		ADDRESS VARCHAR(20),
		BUYER_ID INT,
		SHOP_ID INT,
		PRIMARY KEY(USER_ID)
);
CREATE TABLE BUYER(
		BUYER_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
		NICK_NAME VARCHAR(20),
		PRIMARY KEY (BUYER_ID)
);
CREATE TABLE SHOP(
		SHOP_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
		SHOP_NAME VARCHAR(20),
		DESCRIBE_WORD VARCHAR(30),
		PRIMARY KEY (SHOP_ID)
);
CREATE TABLE WAREHOUSE(
		WAREHOUSE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
		WAREHOUSE_NAME VARCHAR(20),
		ADDRESS VARCHAR(20),
		SHOP_ID INT,
		PRIMARY KEY (WAREHOUSE_ID)
);
CREATE TABLE CART(
		BUYER_ID INT,
		SKU_ID INT,
		PRIMARY KEY (BUYER_ID, SKU_ID)
);
CREATE TABLE PARENT_ORDER(
		PARENT_ORDER_ID INT,
		BUYER_ID INT,
		BUYTIME DATETIME,
		STATUS_ORDER VARCHAR(20),
		ADDRESS VARCHAR(20),
		PRIMARY KEY(PARENT_ORDER_ID)
);
CREATE TABLE SUB_ORDER(
		PARENT_ORDER_ID INT,
		SUB_ORDER_ID INT,
		SKU_ID INT,
		QTY INT,
		SHOP_ID INT,
		MONEY INT,
		EXPRESS_ID VARCHAR(20),
		PRIMARY KEY (PARENT_ORDER_ID, SUB_ORDER_ID)
);
CREATE TABLE SKU(
		SKU_ID INT,
		SKU_NAME VARCHAR(20),
		SKU_DESC VARCHAR(20),
		OBJ_DATA_ID INT,
		PRICE INT,
		SPU_ID INT,
		PRIMARY KEY (SKU_ID)
);
CREATE TABLE SPU(
		SPU_ID INT,
		SPU_NAME VARCHAR(20),
		SPU__DESC VARCHAR(20),
		QTY INT,
		PRIMARY KEY (SPU_ID)
);
CREATE TABLE STORE(
		WAREHOUSE_ID INT,
		SPU_ID INT,
		SKU_ID INT,
		QTY INT,
		PRIMARY KEY(SPU_ID, SKU_ID)
);
CREATE TABLE OBJ_DATA(
		OBJ_DATA_ID INT,
		SKU_ID INT,
		SPU_ID INT,
		DATA VARCHAR(20),
		PRIMARY KEY (OBJ_DATA_ID)
);
CREATE TABLE FIRST_CLASS(
		FIRST_CLASS_ID INT,
		CLASS_DESC VARCHAR(20),
		CLASS_NAME VARCHAR(20),
		PRIMARY KEY (FIRST_CLASS_ID)
);
CREATE TABLE SECOND_CLASS(
		SECOND_CLASS_ID INT,
		CLASS_DESC VARCHAR(20),
		CLASS_NAME VARCHAR(20),
		FIRST_CLASS_ID INT,
		PRIMARY KEY (SECOND_CLASS_ID)
);